#ifndef COIN2FLY_CHAINPARAMSSEEDS_H
#define COIN2FLY_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the pepcash network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x2d,0x4d,0x6b,0x97}, 14444}
};

static SeedSpec6 pnSeed6_test[] = {

};
#endif // COIN2FLY_CHAINPARAMSSEEDS_H

